export interface SeedCastMember {
  name: string;
  role: string;
}

export interface SeedMovie {
  title: string;
  year: number;
  tagline: string;
  runtimeMinutes: number;
  genres: string[];
  director: string;
  cast: SeedCastMember[];
}

export interface SeedPerson {
  name: string;
  born: number;
}

export function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function movieId(title: string, year: number): string {
  return `${slugify(title)}-${year}`;
}

export const SEED_PEOPLE: SeedPerson[] = [
  { name: "Keanu Reeves", born: 1964 },
  { name: "Laurence Fishburne", born: 1961 },
  { name: "Carrie-Anne Moss", born: 1967 },
  { name: "Hugo Weaving", born: 1960 },
  { name: "Lana Wachowski", born: 1965 },
  { name: "Chad Stahelski", born: 1968 },
  { name: "Ian McShane", born: 1942 },
  { name: "Willem Dafoe", born: 1955 },
  { name: "John Leguizamo", born: 1964 },
  { name: "Tom Hanks", born: 1956 },
  { name: "Tim Allen", born: 1953 },
  { name: "Don Rickles", born: 1926 },
  { name: "Wallace Shawn", born: 1943 },
  { name: "John Ratzenberger", born: 1947 },
  { name: "Joan Cusack", born: 1962 },
  { name: "Kelsey Grammer", born: 1955 },
  { name: "Lee Unkrich", born: 1967 },
  { name: "Ned Beatty", born: 1937 },
  { name: "John Lasseter", born: 1957 },
  { name: "Robert Zemeckis", born: 1952 },
  { name: "Robin Wright", born: 1966 },
  { name: "Gary Sinise", born: 1955 },
  { name: "Sally Field", born: 1946 },
  { name: "Mykelti Williamson", born: 1957 },
  { name: "Helen Hunt", born: 1963 },
  { name: "Nick Searcy", born: 1959 },
  { name: "Tim Robbins", born: 1958 },
  { name: "Morgan Freeman", born: 1937 },
  { name: "Bob Gunton", born: 1945 },
  { name: "William Sadler", born: 1950 },
  { name: "Frank Darabont", born: 1959 },
  { name: "Michael Clarke Duncan", born: 1957 },
  { name: "David Morse", born: 1953 },
  { name: "Bonnie Hunt", born: 1961 },
  { name: "Sam Rockwell", born: 1968 },
  { name: "Marlon Brando", born: 1924 },
  { name: "Al Pacino", born: 1940 },
  { name: "James Caan", born: 1940 },
  { name: "Robert Duvall", born: 1931 },
  { name: "Diane Keaton", born: 1946 },
  { name: "Francis Ford Coppola", born: 1939 },
  { name: "Talia Shire", born: 1946 },
  { name: "Robert De Niro", born: 1943 },
  { name: "Michael Mann", born: 1943 },
  { name: "Val Kilmer", born: 1959 },
  { name: "Ashley Judd", born: 1968 },
  { name: "Christian Bale", born: 1974 },
  { name: "Heath Ledger", born: 1979 },
  { name: "Aaron Eckhart", born: 1968 },
  { name: "Gary Oldman", born: 1958 },
  { name: "Michael Caine", born: 1933 },
  { name: "Cillian Murphy", born: 1976 },
  { name: "Christopher Nolan", born: 1970 },
  { name: "Leonardo DiCaprio", born: 1974 },
  { name: "Joseph Gordon-Levitt", born: 1981 },
  { name: "Elliot Page", born: 1987 },
  { name: "Tom Hardy", born: 1977 },
  { name: "Ken Watanabe", born: 1959 },
  { name: "Marion Cotillard", born: 1975 },
  { name: "Matthew McConaughey", born: 1969 },
  { name: "Anne Hathaway", born: 1982 },
  { name: "Jessica Chastain", born: 1977 },
  { name: "Matt Damon", born: 1970 },
  { name: "David Gyasi", born: 1980 },
  { name: "Hugh Jackman", born: 1968 },
  { name: "Scarlett Johansson", born: 1984 },
  { name: "David Bowie", born: 1947 },
  { name: "James Cameron", born: 1954 },
  { name: "Kate Winslet", born: 1975 },
  { name: "Billy Zane", born: 1966 },
  { name: "Kathy Bates", born: 1948 },
  { name: "Martin Scorsese", born: 1942 },
  { name: "Jack Nicholson", born: 1937 },
  { name: "Mark Wahlberg", born: 1971 },
  { name: "Martin Sheen", born: 1940 },
  { name: "Ray Winstone", born: 1957 },
  { name: "Alec Baldwin", born: 1958 },
  { name: "Mark Ruffalo", born: 1967 },
  { name: "Ben Kingsley", born: 1943 },
  { name: "Michelle Williams", born: 1980 },
  { name: "John Travolta", born: 1954 },
  { name: "Samuel L. Jackson", born: 1948 },
  { name: "Uma Thurman", born: 1970 },
  { name: "Bruce Willis", born: 1955 },
  { name: "Tim Roth", born: 1961 },
  { name: "Quentin Tarantino", born: 1963 },
  { name: "Lucy Liu", born: 1968 },
  { name: "Vivica A. Fox", born: 1964 },
  { name: "Daryl Hannah", born: 1960 },
  { name: "David Carradine", born: 1936 },
  { name: "Christopher Walken", born: 1943 },
  { name: "Amy Adams", born: 1974 },
  { name: "Ray Liotta", born: 1954 },
  { name: "Joe Pesci", born: 1943 },
  { name: "Lorraine Bracco", born: 1954 },
  { name: "Sam Neill", born: 1947 },
  { name: "Laura Dern", born: 1967 },
  { name: "Jeff Goldblum", born: 1952 },
  { name: "Richard Attenborough", born: 1923 },
  { name: "Steven Spielberg", born: 1946 },
  { name: "Natalie Portman", born: 1981 },
  { name: "Stephen Rea", born: 1946 },
  { name: "Stephen Fry", born: 1957 },
  { name: "James McTeigue", born: 1967 },
  { name: "Taylor Hackford", born: 1944 },
  { name: "Charlize Theron", born: 1975 },
  { name: "Jonathan Glazer", born: 1965 },
  { name: "Amanda Redman", born: 1957 },
  { name: "Steven Soderbergh", born: 1963 },
  { name: "Gwyneth Paltrow", born: 1972 },
  { name: "Jude Law", born: 1972 },
];

export const SEED_MOVIES: SeedMovie[] = [
  {
    title: "The Matrix",
    year: 1999,
    tagline: "Welcome to the Real World.",
    runtimeMinutes: 136,
    genres: ["Action", "Sci-Fi"],
    director: "Lana Wachowski",
    cast: [
      { name: "Keanu Reeves", role: "Neo" },
      { name: "Laurence Fishburne", role: "Morpheus" },
      { name: "Carrie-Anne Moss", role: "Trinity" },
      { name: "Hugo Weaving", role: "Agent Smith" },
    ],
  },
  {
    title: "The Matrix Reloaded",
    year: 2003,
    tagline: "Free your mind.",
    runtimeMinutes: 138,
    genres: ["Action", "Sci-Fi"],
    director: "Lana Wachowski",
    cast: [
      { name: "Keanu Reeves", role: "Neo" },
      { name: "Laurence Fishburne", role: "Morpheus" },
      { name: "Carrie-Anne Moss", role: "Trinity" },
      { name: "Hugo Weaving", role: "Agent Smith" },
    ],
  },
  {
    title: "The Matrix Revolutions",
    year: 2003,
    tagline: "Everything that has a beginning has an end.",
    runtimeMinutes: 129,
    genres: ["Action", "Sci-Fi"],
    director: "Lana Wachowski",
    cast: [
      { name: "Keanu Reeves", role: "Neo" },
      { name: "Laurence Fishburne", role: "Morpheus" },
      { name: "Carrie-Anne Moss", role: "Trinity" },
      { name: "Hugo Weaving", role: "Agent Smith" },
    ],
  },
  {
    title: "John Wick",
    year: 2014,
    tagline: "Don't set him off.",
    runtimeMinutes: 101,
    genres: ["Action", "Thriller"],
    director: "Chad Stahelski",
    cast: [
      { name: "Keanu Reeves", role: "John Wick" },
      { name: "Ian McShane", role: "Winston" },
      { name: "Willem Dafoe", role: "Marcus" },
      { name: "John Leguizamo", role: "Aurelio" },
    ],
  },
  {
    title: "Toy Story",
    year: 1995,
    tagline: "The toys are back in town.",
    runtimeMinutes: 81,
    genres: ["Animation", "Family", "Comedy"],
    director: "John Lasseter",
    cast: [
      { name: "Tom Hanks", role: "Woody" },
      { name: "Tim Allen", role: "Buzz Lightyear" },
      { name: "Don Rickles", role: "Mr. Potato Head" },
      { name: "Wallace Shawn", role: "Rex" },
      { name: "John Ratzenberger", role: "Hamm" },
    ],
  },
  {
    title: "Toy Story 2",
    year: 1999,
    tagline: "The toys are back!",
    runtimeMinutes: 92,
    genres: ["Animation", "Family", "Comedy"],
    director: "John Lasseter",
    cast: [
      { name: "Tom Hanks", role: "Woody" },
      { name: "Tim Allen", role: "Buzz Lightyear" },
      { name: "Joan Cusack", role: "Jessie" },
      { name: "Kelsey Grammer", role: "Stinky Pete" },
      { name: "Don Rickles", role: "Mr. Potato Head" },
    ],
  },
  {
    title: "Toy Story 3",
    year: 2010,
    tagline: "No toy gets left behind.",
    runtimeMinutes: 103,
    genres: ["Animation", "Family", "Comedy"],
    director: "Lee Unkrich",
    cast: [
      { name: "Tom Hanks", role: "Woody" },
      { name: "Tim Allen", role: "Buzz Lightyear" },
      { name: "Joan Cusack", role: "Jessie" },
      { name: "Ned Beatty", role: "Lotso" },
      { name: "Don Rickles", role: "Mr. Potato Head" },
    ],
  },
  {
    title: "Forrest Gump",
    year: 1994,
    tagline: "Life is like a box of chocolates\u2026 you never know what you're gonna get.",
    runtimeMinutes: 142,
    genres: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    cast: [
      { name: "Tom Hanks", role: "Forrest Gump" },
      { name: "Robin Wright", role: "Jenny Curran" },
      { name: "Gary Sinise", role: "Lieutenant Dan Taylor" },
      { name: "Sally Field", role: "Mrs. Gump" },
      { name: "Mykelti Williamson", role: "Bubba Blue" },
    ],
  },
  {
    title: "Cast Away",
    year: 2000,
    tagline: "At the edge of the world, his journey begins.",
    runtimeMinutes: 143,
    genres: ["Drama", "Adventure"],
    director: "Robert Zemeckis",
    cast: [
      { name: "Tom Hanks", role: "Chuck Noland" },
      { name: "Helen Hunt", role: "Kelly Frears" },
      { name: "Nick Searcy", role: "Stan" },
    ],
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    runtimeMinutes: 142,
    genres: ["Drama"],
    director: "Frank Darabont",
    cast: [
      { name: "Tim Robbins", role: "Andy Dufresne" },
      { name: "Morgan Freeman", role: "Ellis Boyd 'Red' Redding" },
      { name: "Bob Gunton", role: "Warden Norton" },
      { name: "William Sadler", role: "Heywood" },
    ],
  },
  {
    title: "The Green Mile",
    year: 1999,
    tagline: "Miracles do happen.",
    runtimeMinutes: 189,
    genres: ["Drama", "Fantasy"],
    director: "Frank Darabont",
    cast: [
      { name: "Tom Hanks", role: "Paul Edgecomb" },
      { name: "Michael Clarke Duncan", role: "John Coffey" },
      { name: "David Morse", role: "Brutus 'Brutal' Howell" },
      { name: "Bonnie Hunt", role: "Jan Edgecomb" },
      { name: "Sam Rockwell", role: "'Wild Bill' Wharton" },
    ],
  },
  {
    title: "The Godfather",
    year: 1972,
    tagline: "An offer you can't refuse.",
    runtimeMinutes: 175,
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    cast: [
      { name: "Marlon Brando", role: "Don Vito Corleone" },
      { name: "Al Pacino", role: "Michael Corleone" },
      { name: "James Caan", role: "Sonny Corleone" },
      { name: "Robert Duvall", role: "Tom Hagen" },
      { name: "Diane Keaton", role: "Kay Adams" },
    ],
  },
  {
    title: "The Godfather Part II",
    year: 1974,
    tagline: "I don't feel I have to wipe everybody out. Just my enemies.",
    runtimeMinutes: 202,
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    cast: [
      { name: "Al Pacino", role: "Michael Corleone" },
      { name: "Robert Duvall", role: "Tom Hagen" },
      { name: "Diane Keaton", role: "Kay Adams" },
      { name: "Robert De Niro", role: "Vito Corleone" },
      { name: "Talia Shire", role: "Connie Corleone" },
    ],
  },
  {
    title: "Heat",
    year: 1995,
    tagline: "A Los Angeles crime saga.",
    runtimeMinutes: 170,
    genres: ["Crime", "Thriller"],
    director: "Michael Mann",
    cast: [
      { name: "Al Pacino", role: "Vincent Hanna" },
      { name: "Robert De Niro", role: "Neil McCauley" },
      { name: "Val Kilmer", role: "Chris Shiherlis" },
      { name: "Ashley Judd", role: "Charlene" },
    ],
  },
  {
    title: "The Dark Knight",
    year: 2008,
    tagline: "Why so serious?",
    runtimeMinutes: 152,
    genres: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    cast: [
      { name: "Christian Bale", role: "Bruce Wayne" },
      { name: "Heath Ledger", role: "The Joker" },
      { name: "Aaron Eckhart", role: "Harvey Dent" },
      { name: "Gary Oldman", role: "Commissioner Gordon" },
      { name: "Michael Caine", role: "Alfred" },
      { name: "Morgan Freeman", role: "Lucius Fox" },
      { name: "Cillian Murphy", role: "Jonathan Crane" },
    ],
  },
  {
    title: "Inception",
    year: 2010,
    tagline: "Your mind is the scene of the crime.",
    runtimeMinutes: 148,
    genres: ["Sci-Fi", "Action", "Thriller"],
    director: "Christopher Nolan",
    cast: [
      { name: "Leonardo DiCaprio", role: "Dom Cobb" },
      { name: "Joseph Gordon-Levitt", role: "Arthur" },
      { name: "Elliot Page", role: "Ariadne" },
      { name: "Tom Hardy", role: "Eames" },
      { name: "Ken Watanabe", role: "Saito" },
      { name: "Marion Cotillard", role: "Mal" },
      { name: "Cillian Murphy", role: "Robert Fischer" },
      { name: "Michael Caine", role: "Miles" },
    ],
  },
  {
    title: "Interstellar",
    year: 2014,
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    runtimeMinutes: 169,
    genres: ["Sci-Fi", "Drama"],
    director: "Christopher Nolan",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper" },
      { name: "Anne Hathaway", role: "Dr. Amelia Brand" },
      { name: "Jessica Chastain", role: "Murph" },
      { name: "Michael Caine", role: "Professor Brand" },
      { name: "Matt Damon", role: "Dr. Mann" },
      { name: "David Gyasi", role: "Romilly" },
    ],
  },
  {
    title: "The Prestige",
    year: 2006,
    tagline: "Are you watching closely?",
    runtimeMinutes: 130,
    genres: ["Drama", "Mystery"],
    director: "Christopher Nolan",
    cast: [
      { name: "Hugh Jackman", role: "Robert Angier" },
      { name: "Christian Bale", role: "Alfred Borden" },
      { name: "Michael Caine", role: "Cutter" },
      { name: "Scarlett Johansson", role: "Olivia Wenscombe" },
      { name: "David Bowie", role: "Nikola Tesla" },
    ],
  },
  {
    title: "Titanic",
    year: 1997,
    tagline: "Nothing on Earth could come between them.",
    runtimeMinutes: 194,
    genres: ["Romance", "Drama"],
    director: "James Cameron",
    cast: [
      { name: "Leonardo DiCaprio", role: "Jack Dawson" },
      { name: "Kate Winslet", role: "Rose DeWitt Bukater" },
      { name: "Billy Zane", role: "Cal Hockley" },
      { name: "Kathy Bates", role: "Molly Brown" },
    ],
  },
  {
    title: "The Departed",
    year: 2006,
    tagline: "Cops or criminals. When you're facing a loaded gun, what's the difference?",
    runtimeMinutes: 151,
    genres: ["Crime", "Thriller"],
    director: "Martin Scorsese",
    cast: [
      { name: "Leonardo DiCaprio", role: "Billy Costigan" },
      { name: "Matt Damon", role: "Colin Sullivan" },
      { name: "Jack Nicholson", role: "Frank Costello" },
      { name: "Mark Wahlberg", role: "Sergeant Dignam" },
      { name: "Martin Sheen", role: "Captain Queenan" },
      { name: "Ray Winstone", role: "French" },
      { name: "Alec Baldwin", role: "Captain Ellerby" },
    ],
  },
  {
    title: "Shutter Island",
    year: 2010,
    tagline: "Some places never let you go.",
    runtimeMinutes: 138,
    genres: ["Mystery", "Thriller"],
    director: "Martin Scorsese",
    cast: [
      { name: "Leonardo DiCaprio", role: "Teddy Daniels" },
      { name: "Mark Ruffalo", role: "Chuck Aule" },
      { name: "Ben Kingsley", role: "Dr. Cawley" },
      { name: "Michelle Williams", role: "Dolores Chanal" },
    ],
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    tagline: "You won't know the facts until you've seen the fiction.",
    runtimeMinutes: 154,
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    cast: [
      { name: "John Travolta", role: "Vincent Vega" },
      { name: "Samuel L. Jackson", role: "Jules Winnfield" },
      { name: "Uma Thurman", role: "Mia Wallace" },
      { name: "Bruce Willis", role: "Butch Coolidge" },
      { name: "Tim Roth", role: "Pumpkin" },
    ],
  },
  {
    title: "Kill Bill: Vol. 1",
    year: 2003,
    tagline: "The bride is back for unfinished business.",
    runtimeMinutes: 111,
    genres: ["Action", "Crime"],
    director: "Quentin Tarantino",
    cast: [
      { name: "Uma Thurman", role: "The Bride" },
      { name: "Lucy Liu", role: "O-Ren Ishii" },
      { name: "David Carradine", role: "Bill" },
      { name: "Vivica A. Fox", role: "Vernita Green" },
      { name: "Daryl Hannah", role: "Elle Driver" },
    ],
  },
  {
    title: "Catch Me If You Can",
    year: 2002,
    tagline: "The true story of a real fake.",
    runtimeMinutes: 141,
    genres: ["Crime", "Drama"],
    director: "Steven Spielberg",
    cast: [
      { name: "Leonardo DiCaprio", role: "Frank Abagnale Jr." },
      { name: "Tom Hanks", role: "Carl Hanratty" },
      { name: "Christopher Walken", role: "Frank Abagnale Sr." },
      { name: "Amy Adams", role: "Brenda Strong" },
      { name: "Martin Sheen", role: "Roger Strong" },
    ],
  },
  {
    title: "Goodfellas",
    year: 1990,
    tagline: "Three decades of life in the mob.",
    runtimeMinutes: 145,
    genres: ["Crime", "Drama"],
    director: "Martin Scorsese",
    cast: [
      { name: "Ray Liotta", role: "Henry Hill" },
      { name: "Robert De Niro", role: "Jimmy Conway" },
      { name: "Joe Pesci", role: "Tommy DeVito" },
      { name: "Lorraine Bracco", role: "Karen Hill" },
      { name: "Samuel L. Jackson", role: "Stacks Edwards" },
    ],
  },
  {
    title: "Jurassic Park",
    year: 1993,
    tagline: "An adventure 65 million years in the making.",
    runtimeMinutes: 127,
    genres: ["Sci-Fi", "Adventure"],
    director: "Steven Spielberg",
    cast: [
      { name: "Sam Neill", role: "Dr. Alan Grant" },
      { name: "Laura Dern", role: "Dr. Ellie Sattler" },
      { name: "Jeff Goldblum", role: "Dr. Ian Malcolm" },
      { name: "Richard Attenborough", role: "John Hammond" },
      { name: "Samuel L. Jackson", role: "Ray Arnold" },
    ],
  },
  {
    title: "V for Vendetta",
    year: 2005,
    tagline: "People should not be afraid of their governments. Governments should be afraid of their people.",
    runtimeMinutes: 132,
    genres: ["Sci-Fi", "Action", "Thriller"],
    director: "James McTeigue",
    cast: [
      { name: "Hugo Weaving", role: "V" },
      { name: "Natalie Portman", role: "Evey Hammond" },
      { name: "Stephen Rea", role: "Inspector Finch" },
      { name: "Stephen Fry", role: "Deitrich" },
    ],
  },
  {
    title: "The Devil's Advocate",
    year: 1997,
    tagline: "Evil has its winning ways.",
    runtimeMinutes: 144,
    genres: ["Thriller", "Drama"],
    director: "Taylor Hackford",
    cast: [
      { name: "Keanu Reeves", role: "Kevin Lomax" },
      { name: "Al Pacino", role: "John Milton" },
      { name: "Charlize Theron", role: "Mary Ann Lomax" },
    ],
  },
  {
    title: "Sexy Beast",
    year: 2000,
    tagline: "There's a new king of the jungle.",
    runtimeMinutes: 89,
    genres: ["Crime", "Drama"],
    director: "Jonathan Glazer",
    cast: [
      { name: "Ray Winstone", role: "Gal" },
      { name: "Ben Kingsley", role: "Don Logan" },
      { name: "Ian McShane", role: "Teddy Bass" },
      { name: "Amanda Redman", role: "Deedee" },
    ],
  },
  {
    title: "Contagion",
    year: 2011,
    tagline: "Nothing spreads like fear.",
    runtimeMinutes: 106,
    genres: ["Drama", "Thriller"],
    director: "Steven Soderbergh",
    cast: [
      { name: "Matt Damon", role: "Mitch Emhoff" },
      { name: "Kate Winslet", role: "Dr. Erin Mears" },
      { name: "Laurence Fishburne", role: "Dr. Ellis Cheever" },
      { name: "Marion Cotillard", role: "Dr. Leonora Orantes" },
      { name: "Gwyneth Paltrow", role: "Beth Emhoff" },
      { name: "Jude Law", role: "Alan Krumwiede" },
    ],
  },
];
